TrainingReg As screen:
    OnVisible: |+
        =UpdateContext({UserChecki:false});
        UpdateContext({UserCheckk:!UserCheckk});
        UpdateContext({UserCheck:false}); 
        Refresh(TrainingRegistration);
        Concurrent(
        Reset(training_prog_gal),
        
        ClearCollect(myTrainingReg, ShowColumns(TrainingRegistration, "ID","Title", "TrainingModule", "StartDate", "BeltType", "Function")),
        
        ClearCollect(myProfileProgress,ShowColumns(SortByColumns(TrainingProfileProgress_Lean, "Modified",SortOrder.Descending), "ID","Program", "User", "Title", "TimeDura", "Progress", "DateTime", "Modified", "TotalScore", "Reg_ID_ref")),
        
        ClearCollect(myTrainingTopics, ShowColumns('Training Topics', "ID","Title", "Vid_Dur", "Remarks"))
        
        );
        UpdateContext({UserCheckk:!UserCheckk})
        

    "gal_userCheck As gallery.'BrowseLayout_Vertical_OneTextVariant_ver4.0'":
        Height: =196
        Items: |-
            =Filter(myTrainingReg, TrainingModule=training_prog_gal.Selected.Value ||
                        TrainingModule = training_prog_gal.Selected.Value & " Annual Certification",
                        Title=varUserEmail)
        Layout: =Layout.Vertical
        TemplatePadding: =0
        TemplateSize: =Min(96, Self.Height - 60)
        Visible: =false
        Width: =1000
        X: =157
        Y: =443
        ZIndex: =1

        Title8 As label:
            Height: =41
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.Title
            VerticalAlign: =VerticalAlign.Top
            Width: =223
            X: =32
            Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
            ZIndex: =1

        Separator9 As rectangle:
            Height: =1
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - 1
            ZIndex: =3

        Title8_1 As label:
            Height: =41
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.TrainingModule
            VerticalAlign: =VerticalAlign.Top
            Width: =118
            X: =255
            Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
            ZIndex: =4

        Title8_4 As label:
            Height: =41
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.Function.Value
            VerticalAlign: =VerticalAlign.Top
            Width: =442
            X: =373
            Y: =27
            ZIndex: =5

    Rectangle1_14 As rectangle:
        Height: =115
        Width: =1366
        Y: =653
        ZIndex: =6

    Label2_10 As label:
        Align: =LayoutAlignItems.Center
        Color: =RGBA(255, 255, 255, 1)
        DisplayMode: =DisplayMode.View
        FontWeight: =FontWeight.Bold
        Height: =86
        Size: =36
        Text: ="PEX Training"
        Width: =1182
        X: =184
        Y: =674
        ZIndex: =8

    Image2 As image:
        Image: =SSlogo
        X: =480
        Y: =667
        ZIndex: =9

    training_prog_gal As gallery.galleryHorizontal:
        Default: ={}
        DisplayMode: =If(!UserCheck,DisplayMode.Edit,DisplayMode.View)
        Height: =250
        Items: =["LEAN", "Six Sigma", "ESD"]
        OnSelect: |-
            =UpdateContext({UserCheck:true});
            UpdateContext({UserChecki:false});
            Set(varTrainingSelect, ThisItem)
        TemplateFill: |-
            =//RGBA(0, 0, 0, 0)
            If(ThisItem.IsSelected,RGBA(215,213,240,1),RGBA(215, 223, 240, 1))
        TemplateSize: =330
        Visible: =!UserCheckk
        Width: =1018
        X: =148
        Y: =179
        ZIndex: =12

        prog_lbl As label:
            Align: =LayoutAlignItems.Center
            DisplayMode: =If(ThisItem.Value="LEAN", DisplayMode.Edit,DisplayMode.Disabled)
            FontWeight: =FontWeight.Bold
            Height: =171
            OnSelect: =Select(Parent)
            Size: =50
            Text: =ThisItem.Value
            Width: =309
            X: =5
            Y: =36
            ZIndex: =1

        Circle2 As circle:
            DisplayMode: =DisplayMode.View
            Fill: =If(ThisItem.Value="ESD" || varUserEmail in ["Danilo Nonod Jr.", "Rosalie Abono"] , RGBA(39, 113, 194, 1),RGBA(0, 0, 0, 0))
            Height: =23
            OnSelect: =Select(Parent)
            Visible: =If(ThisItem.IsSelected, true, false)
            Width: =24
            X: =5
            ZIndex: =2

        Button16 As button:
            Fill: =Color.Transparent
            Height: =Parent.TemplateHeight
            HoverFill: =Self.Fill
            OnSelect: |-
                =UpdateContext({UserCheck:true})
                  /*  First(
                        Filter(
                            TrainingRegistration,
                            TrainingModule = ThisItem.Value ||
                            TrainingModule = ThisItem.Value & " Annual Certification" &&
                            Title = varUserEmail
                        )
                    ).Title = varUserEmail,
                    Navigate(
                        HomeTrainingList,
                        ScreenTransition.CoverRight
                    );
                    Set(HomeListTopic,Filter(AddColumns(myTrainingTopics, "NameRec", LookUp(myProfileProgress, Title = myTrainingTopics[@Title] && User=varUserEmail),
                "NameRe", LookUp(TrainingRegistration, Title= varUserEmail)
                ), Vid_Dur = training_prog_gal.Selected.Value)); 
                Set(ID_gal, Last(Filter(TrainingRegistration, Title=varUserEmail)).ID),
                    ResetForm(TrainingRegForm);
                    Set(
                        varFormTraining,
                        Defaults(TrainingRegistration)
                    );
                    Set(
                        varFormModeTraining,
                        FormMode.New
                    );
                    Set(
                        varDisplayView,
                        DisplayMode.View
                    );
                    Reset(timer_2);
                    Navigate(
                        TrainingReg_1,
                        ScreenTransition.CoverRight
                    )
                )*/
            PressedFill: =Self.Fill
            Size: =40
            Text: =
            Width: =Parent.TemplateWidth
            ZIndex: =3

    Icon18 As icon.BackArrow:
        Icon: =Icon.BackArrow
        OnSelect: =Navigate(HomeUser,ScreenTransition.None)
        Visible: =If(varUserEmail="Danilo Nonod Jr.", true, false)
        X: =132
        Y: =25
        ZIndex: =14

    TR_header_grp As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =14

        Rectangle1_12 As rectangle:
            Height: =115
            Width: =1366
            ZIndex: =1

        Label2_9 As label:
            Color: =RGBA(255, 255, 255, 1)
            DisplayMode: =DisplayMode.View
            Height: =115
            Text: ="Welcome, " & varUserEmail
            Width: =120
            X: =1244
            ZIndex: =2

        Image1_3 As image:
            Height: =66
            Image: =HDD_1
            Width: =65
            X: =31
            Y: =16
            ZIndex: =3

        img_user As image:
            Image: =varUserimg
            RadiusBottomLeft: =img_user.Height
            RadiusBottomRight: =img_user.Height
            RadiusTopLeft: =img_user.Height
            RadiusTopRight: =img_user.Height
            X: =1144
            Y: =7
            ZIndex: =13

    Timer4 As timer:
        AutoPause: =false
        Duration: =5000
        OnTimerEnd: |+
            =If(!IsEmpty(gal_userCheck.AllItems), Navigate(
                    HomeTrainingList,
                    ScreenTransition.CoverRight
                );
                UpdateContext({UserCheck:false}); 
                Set(ID_gal, Last(Filter(myTrainingReg, Title=varUserEmail)).ID);
                Set(HomeListTopic,Filter(AddColumns(myTrainingTopics, "NameRec", LookUp(myProfileProgress, Title = myTrainingTopics[@Title] && User=varUserEmail && Reg_ID_ref=ID_gal),
            "NameRe", LookUp(myTrainingReg, Title= varUserEmail)
            ), Vid_Dur = training_prog_gal.Selected.Value))
            ,
            ResetForm(TrainingRegForm);
                Set(
                    varFormTraining,
                    Defaults(TrainingRegistration)
                );
                Set(
                    varFormModeTraining,
                    FormMode.New
                );
                Set(
                    varDisplayView,
                    DisplayMode.View
                );
                Reset(timer_2);
                
            UpdateContext({UserCheck:false});    
            UpdateContext({UserChecki:true})
            );
            
        Start: =UserCheck
        Visible: =false
        X: =96
        Y: =697
        ZIndex: =15

    locShowSpinner_5 As image:
        Image: =spinner
        Visible: =UserCheck
        X: =607
        Y: =443
        ZIndex: =16

    locShowSpinner_6 As image:
        Image: =spinner
        Visible: =UserCheckk
        X: =570
        Y: =278
        ZIndex: =17

    Label50 As label:
        Align: =LayoutAlignItems.Center
        Height: =47
        Text: ="Checking Record..."
        Visible: =UserCheck
        Width: =240
        X: =537
        Y: =524
        ZIndex: =18

    Icon26 As icon.CheckBadge:
        Height: =96
        Icon: =Icon.CheckBadge
        OnSelect: |-
            =Navigate(
                    TrainingReg_1,
                    ScreenTransition.UnCoverRight);
            UpdateContext({UserChecki:!UserChecki})        
        Visible: =UserChecki
        Width: =111
        X: =955
        Y: =489
        ZIndex: =19

    Label50_1 As label:
        Align: =LayoutAlignItems.Center
        Height: =47
        Text: ="Click to proceed registration"
        Visible: =UserChecki
        Width: =240
        X: =890
        Y: =443
        ZIndex: =20

    popfreeze_2 As rectangle:
        Fill: =RGBA(56, 96, 178, 0.1)
        Height: =768
        Visible: =UserCheckk
        Width: =1366
        ZIndex: =21

