"Training_Complete As screen.'tabletLayout_Success_ver3.0'":
    OnVisible: =ClearCollect(myProfileProgress, ShowColumns(TrainingProfileProgress_Lean,"ID","Program", "User", "Title", "TimeDura", "Progress", "DateTime", "Modified", "TotalScore", "Reg_ID_ref"))

    iconCircle2_1 As circle.Circle:
        X: =633
        Y: =220
        ZIndex: =1

    iconCheck2_1 As icon.Check:
        Height: =iconCircle2_1.Height
        Icon: =Icon.Check
        PaddingBottom: =Self.PaddingTop
        PaddingLeft: =Self.PaddingTop
        PaddingRight: =Self.PaddingTop
        PaddingTop: =24
        Width: =iconCircle2_1.Width
        X: =633
        Y: =220
        ZIndex: =2

    Rectangle1_29 As rectangle:
        Height: =115
        Width: =1366
        Y: =653
        ZIndex: =5

    Label2_19 As label:
        Align: =LayoutAlignItems.Center
        DisplayMode: =DisplayMode.View
        FontWeight: =FontWeight.Bold
        Height: =86
        Size: =36
        Text: ="Your Session was successfully saved!!!"
        Width: =1182
        X: =123
        Y: =341
        ZIndex: =6

    Timer2_1 As timer:
        AutoStart: =true
        Duration: =10000
        OnTimerEnd: =Navigate(HomeTrainingLean_HomeExam)
        Start: |+
            =false
            
        Visible: =false
        X: =135
        Y: =690
        ZIndex: =7

    LblSuccessMsg2_4 As label:
        Align: =Align.Center
        AutoHeight: =true
        Height: =iconCircle2_1.Height
        Size: =20
        Text: ="Redirecting to QUIZ and EXERCISE in " & RoundUp(10- Timer2_1.Value/1000,0) & "s"
        Width: =Parent.Width * 0.75
        X: =186
        Y: =518
        ZIndex: =8

    Label2_23 As label:
        Align: =LayoutAlignItems.Center
        Color: =RGBA(255, 255, 255, 1)
        DisplayMode: =DisplayMode.View
        Fill: =RGBA(255, 191, 0, 1)
        FontWeight: =FontWeight.Bold
        Height: =86
        Size: =36
        Text: =gal_topic.Selected.Title
        Width: =1182
        X: =108
        Y: =427
        ZIndex: =9

    HTVid_header_grp_1 As group:
        Height: =5
        Width: =5
        X: =40
        Y: =20
        ZIndex: =13

        Rectangle1_27 As rectangle:
            Height: =89
            Width: =1366
            Y: =2
            ZIndex: =10

        Label2_18 As label:
            Color: =RGBA(255, 255, 255, 1)
            DisplayMode: =DisplayMode.View
            Height: =89
            Text: ="Welcome, " & varUserEmail
            Width: =120
            X: =1244
            Y: =2
            ZIndex: =11

        img_user_3 As image:
            Height: =77
            Image: =varUserimg
            RadiusBottomLeft: =img_user_3.Height
            RadiusBottomRight: =img_user_3.Height
            RadiusTopLeft: =img_user_3.Height
            RadiusTopRight: =img_user_3.Height
            Width: =img_user_3.Height
            X: =1160
            Y: =8
            ZIndex: =12

